name: Release Development Build on Test PyPI

on:
  push:
    branches: [ main ]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    # environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      
      - name: Update version with build number
        run: |
          VERSION=$(grep -Po "__version__ = \"\K[^\"]+" src/stockbeta/__about__.py)
          echo "VERSION=${VERSION}.dev${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          sed -i "s/__version__ = .*/__version__ = \"${VERSION}.dev${GITHUB_RUN_NUMBER}\"/" src/stockbeta/__about__.py
    #   This will transform version numbers like this: 0.0.1 → 0.0.1.dev42
    #     (where 42 is the GitHub Actions run number) PyPI doesn't allow you to
    #     publish a version that already exists, so we need to increment the
    #     version number.  

      - name: Build package
        run: hatch build
      
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

